export const POST_MESSAGE_READ_LINE = "POST_MESSAGE_READ_LINE";
export const POST_MESSAGE_IFRAME_INIT ="POST_MESSAGE_IFRAME_INIT";
export const POST_MESSAGE_PROJECT_LIFE_DRAW = "POST_MESSAGE_PROJECT_LIFE_DRAW";